### ISSUE TITLE
Consider moving a subset of the dependencies to extras

### ISSUE THREAD

**Issue by caniko** [Tobi-De/fastapi-users-tortoise#1]
I am splitting my user models from my fastapi app in a separate package, and was hoping to use the model classes ONLY for the user model package.

Could we outline what packages are nesccessary to inherit from the models? I can make a PR right away with the adapted `pyproject.toml` file.

The new installation method for the full dependency tree could be:
```shell
pip install <name>[full]
```

**Comment by Tobi-De** [comment]
Ok, I know you closed it, but I'm just curious what exactly was your issue @caniko ? 

>Could we outline what packages are nesccessary to inherit from the models? I can make a PR right away with the adapted pyproject.toml file.

What exactly did you mean?

**Comment by caniko** [comment]
I think the issue is on the poetry side; I use poetry. It installs everything listed as optional in `pyproject.toml`

**Comment by Tobi-De** [comment]
Oh I see you use poetry, the tool used to manage dependencies here is [flit](https://flit.pypa.io/en/latest/), frankly I don't know much about it, I just kept it because it was the one used in the cookiecutter I used to start the project.

**Comment by caniko** [comment]
Never got into the cookiecutter paradigm too much to get into/reverse engineer; I should give it another shot some time when I am doing a small project. Poetry has a lot of bells and whistles in one framework, which is what makes it so appealing to me.

**Comment by Tobi-De** [comment]
Yes, I would much rather use poetry myself, but flit worked so I left it there.
Cookiecutters can be useful to avoid boleiplate, I always use them when I start a django project, but yes I don't like when they are too packed, it can be confusing.
